//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conecta4AppConsola {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Conecta4ResourceES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Conecta4ResourceES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conecta4AppConsola.Conecta4ResourceES", typeof(Conecta4ResourceES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1) Manual (Ninguno)
        ///2) IA Aleatoria
        ///3) IA Lista.
        /// </summary>
        internal static string Algoritmo {
            get {
                return ResourceManager.GetString("Algoritmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algotirmo que utilizará el primer jugador: .
        /// </summary>
        internal static string Algoritmo1 {
            get {
                return ResourceManager.GetString("Algoritmo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algotirmo que utilizará el segundo jugador: .
        /// </summary>
        internal static string Algoritmo2 {
            get {
                return ResourceManager.GetString("Algoritmo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La columna no es válida..
        /// </summary>
        internal static string ColumnaInvalida {
            get {
                return ResourceManager.GetString("ColumnaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce la dimensión del tablero: .
        /// </summary>
        internal static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empate..
        /// </summary>
        internal static string Empate {
            get {
                return ResourceManager.GetString("Empate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ganador es: .
        /// </summary>
        internal static string Ganador {
            get {
                return ResourceManager.GetString("Ganador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a , introduzca la columna: .
        /// </summary>
        internal static string InputColumna {
            get {
                return ResourceManager.GetString("InputColumna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del primer jugador: .
        /// </summary>
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del segundo jugador: .
        /// </summary>
        internal static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
    }
}
